version: "3.7"
services:
    db:
        image: mysql
        ports: 
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=rootPassword
          - MYSQL_USER=user
          - MYSQL_PASSWORD=userPassword
        volumes:
          - ./infra/scripts:/docker-entrypoint-initdb.d
          - ./infra/conf:/etc/mysql/conf.d
          # - persistent:/var/lib/mysql
          - ./infra/db:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "88:80"
        volumes:
            - ./src:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
# volumes:
#     persistent:
