version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userPassword
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d/

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          - PMA_HOST=db
          # - PMA_ARBITRARY=1
      depends_on:
          - db

  apache:
      image: php:8.0-apache
      volumes:
          - ../src:/var/www/html/
      ports:
          - 80:80
      depends_on:
      - db